In [5]:
import numpy as np
np.arange(0,10,2)
np.linspace(0,10,2)

array([ 0., 10.])

In [2]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
np.zeros((2,2)) # should pass tuple as dimens

array([[0., 0.],
       [0., 0.]])

In [4]:
np.random.rand(3,3)

array([[0.80326667, 0.4660242 , 0.30605983],
       [0.00086092, 0.44076893, 0.09962798],
       [0.26609334, 0.40361622, 0.46684461]])

In [7]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr[0:5]=100
print(arr) # braod cast possible

[100 100 100 100 100   5   6   7   8   9  10]


In [11]:
list_1 = [i for i in range(0,11)]
print(list_1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [17]:
list_1[0:5]=100
print(list_1)

TypeError: can only assign an iterable

In [19]:
arr_copy = arr.copy()
print(arr_copy)
arr_copy[:]=66
print(arr_copy)
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]
[66 66 66 66 66 66 66 66 66 66 66]
[100 100 100 100 100   5   6   7   8   9  10]


In [21]:
new_arr=np.arange(0,11)
print(new_arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [23]:
copy_1 = new_arr[0:6]
print(copy_1)

[0 1 2 3 4 5]


In [25]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [29]:
arr_2d[:,:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [30]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])